<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Ledger - {{ $retailer->name }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; color: #333; line-height: 1.4; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #ef4444; padding-bottom: 10px; }
        .header h1 { color: #ef4444; margin: 0; font-size: 24px; }
        .business-info { margin-bottom: 20px; }
        .summary-box { background: #f9fafb; padding: 15px; border-radius: 8px; margin-bottom: 20px; border: 1px solid #e5e7eb; }
        .summary-table { width: 100%; border-collapse: collapse; }
        .summary-table td { padding: 5px; }
        .summary-value { font-weight: bold; text-align: right; }
        
        table.ledger { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.ledger th { background: #fee2e2; padding: 10px; text-align: left; border: 1px solid #fecaca; font-size: 10px; text-transform: uppercase; color: #991b1b; }
        table.ledger td { padding: 10px; border: 1px solid #f3f4f6; }
        .text-right { text-align: right; }
        .debit { color: #dc2626; }
        .credit { color: #059669; }
        .running-balance { font-weight: bold; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #9ca3af; }
    </style>
</head>
<body>
    <div class="header">
        <h1>SWDMS - RETAILER LEDGER</h1>
        <p>Statement Date: {{ date('M d, Y') }}</p>
    </div>

    <div class="business-info">
        <table style="width: 100%;">
            <tr>
                <td style="width: 50%;">
                    <strong>Retailer Details:</strong><br>
                    {{ $retailer->name }}<br>
                    {{ $retailer->contact_person ? 'Attn: '.$retailer->contact_person : '' }}<br>
                    {{ $retailer->address }}<br>
                    Phone: {{ $retailer->phone }}
                </td>
                <td style="width: 50%; text-align: right; vertical-align: top;">
                    <strong>Wholesaler:</strong><br>
                    {{ auth()->user()->business_name ?? auth()->user()->name }}<br>
                    {{ auth()->user()->business_address }}<br>
                    GSTIN: {{ auth()->user()->gstin }}
                </td>
            </tr>
        </table>
    </div>

    <div class="summary-box">
        <table class="summary-table">
            <tr>
                <td>Total Billed (Orders)</td>
                <td class="summary-value">₹{{ number_format($retailer->total_billed ?? $orders->sum('total_amount'), 2) }}</td>
            </tr>
            <tr>
                <td>Total Received (Payments)</td>
                <td class="summary-value credit">₹{{ number_format($retailer->total_paid ?? $payments->sum('amount_paid'), 2) }}</td>
            </tr>
            <tr>
                <td style="font-size: 16px; font-weight: bold;">Outstanding Balance</td>
                <td class="summary-value debit" style="font-size: 16px;">₹{{ number_format($retailer->current_due, 2) }}</td>
            </tr>
        </table>
    </div>

    <table class="ledger">
        <thead>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th class="text-right">Debit (+)</th>
                <th class="text-right">Credit (-)</th>
                <th class="text-right">Balance</th>
            </tr>
        </thead>
        <tbody>
            @php $runningBalance = 0; @endphp
            @foreach($orders->merge($payments)->sortBy('created_at') as $item)
                @php 
                    $isOrder = isset($item->total_amount);
                    $debit = $isOrder ? $item->total_amount : 0;
                    $credit = !$isOrder ? $item->amount_paid : 0;
                    $runningBalance += ($debit - $credit);
                @endphp
                <tr>
                    <td>{{ $item->created_at->format('d/m/Y') }}</td>
                    <td>
                        {{ $isOrder ? "Order #{$item->id}" : "Payment Recv" }}
                        @if(!$isOrder && $item->payment_mode)
                            <br><small style="color: #6b7280;">({{ $item->payment_mode }})</small>
                        @endif
                    </td>
                    <td class="text-right debit">{{ $debit > 0 ? '₹'.number_format($debit, 2) : '-' }}</td>
                    <td class="text-right credit">{{ $credit > 0 ? '₹'.number_format($credit, 2) : '-' }}</td>
                    <td class="text-right running-balance">₹{{ number_format($runningBalance, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by SWDMS - Smart Wholesale Distribution Management System
    </div>
</body>
</html>
